server:
  address: ":8080"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

database:
  default:
    link: "mysql:root:password@tcp(127.0.0.1:3306)/ecommerce?charset=utf8mb4&parseTime=True&loc=Local"
    debug: true

redis:
  default:
    address: 127.0.0.1:6379
    db: 0

logger:
  level: "debug"
  stdout: true
